[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "3PwTwex4PiS1J1B5qrKxq77ZkBz5G5zmGhs3tfKneU32"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vanessa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
